FROM golang:1.20-alpine AS builder
WORKDIR /src

COPY . ./

RUN go mod download -x all
RUN go build -o /app/api .

# ---

FROM alpine:edge
WORKDIR /app
RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /src/data/migrations /app/data/migrations
COPY --from=builder /app/api /app

EXPOSE 4000
CMD ["/app/api", "serve"]